---
language: node_js

sudo: false

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

cache:
  directories:
    - node_modules

install:
  - npm install -g bower
  - npm install
  - ./packaging/select-ember-version.js

script:
  - npm test

env:
  matrix:
    - EMBER_CHANNEL=release
    - EMBER_CHANNEL=beta
    - EMBER_CHANNEL=canary
    - EMBER_CHANNEL=canary HTMLBARS=true